config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models_new/colpali_post_proj_cluster_factor9
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColPaliProcessor
    pretrained_model_name_or_path:  "/mnt/hwfile/mllm/mayubo/paligemma-3b-mix-448"
    max_length: 50
  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColPali
    pretrained_model_name_or_path: "/mnt/hwfile/mllm/mayubo/paligemma-3b-mix-448"
    torch_dtype: "bfloat16"
    attn_implementation: "flash_attention_2"
    pooling_strategy: post_proj_cluster
    pool_size: 9
#    quantization_confi
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_train_set
  eval_dataset_loader: !import ../data/test_data.yaml
  proj_lora: false

  max_length: 50
  run_train: false
  run_eval: true
  # pretrained_peft_model_name_or_path: /mnt/petrelfs/mayubo/colpali/models_new/colpali_original/checkpoint-2310
  pretrained_peft_model_name_or_path: /mnt/petrelfs/mayubo/colpali/models_new/colpali_post_proj_cluster_factor9/checkpoint-2310
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.ColbertPairwiseCELoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 5
    per_device_train_batch_size: 32
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    per_device_eval_batch_size: 8
    eval_strategy: "steps"
    dataloader_num_workers: 8
    save_steps: 500
    logging_steps: 1
    eval_steps: 100
    warmup_steps: 100
    learning_rate: 5e-4
    save_total_limit: 1
    report_to: "wandb"
  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$'